use std::fmt;

use super::combo::{ModType, Side};

const UNKNOWN_WIRE_PREFIX: u16 = 0x8000;

/// Platform-neutral key identity used by the hotkey core.
///
/// Platform providers map OS-specific keycodes to this enum at the boundary.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Key {
    F(u8),
    Char(char),
    Digit(u8),
    Space,
    Tab,
    Escape,
    Return,
    Delete,
    Backspace,
    ArrowUp,
    ArrowDown,
    ArrowLeft,
    ArrowRight,
    Punct(char),
    Modifier(ModType, Side),
    Unknown(u16),
}

impl Key {
    pub fn modifier(self) -> Option<(ModType, Side)> {
        match self {
            Self::Modifier(ty, side) => Some((ty, side)),
            _ => None,
        }
    }

    pub fn wire_code(self) -> u16 {
        match self {
            Self::F(n @ 1..=20) => 0x0100 + n as u16,
            Self::Char(c @ 'a'..='z') => c as u16,
            Self::Digit(n @ 0..=9) => b'0' as u16 + n as u16,
            Self::Space => 0x0020,
            Self::Tab => 0x0009,
            Self::Escape => 0x001b,
            Self::Return => 0x000d,
            Self::Delete => 0x007f,
            Self::Backspace => 0x0008,
            Self::ArrowUp => 0x0201,
            Self::ArrowDown => 0x0202,
            Self::ArrowLeft => 0x0203,
            Self::ArrowRight => 0x0204,
            Self::Punct(c) => c as u16,
            Self::Modifier(ModType::Cmd, Side::Left) => 0x0301,
            Self::Modifier(ModType::Cmd, Side::Right) => 0x0302,
            Self::Modifier(ModType::Ctrl, Side::Left) => 0x0303,
            Self::Modifier(ModType::Ctrl, Side::Right) => 0x0304,
            Self::Modifier(ModType::Opt, Side::Left) => 0x0305,
            Self::Modifier(ModType::Opt, Side::Right) => 0x0306,
            Self::Modifier(ModType::Shift, Side::Left) => 0x0307,
            Self::Modifier(ModType::Shift, Side::Right) => 0x0308,
            Self::Unknown(code) => UNKNOWN_WIRE_PREFIX | code,
            _ => 0xffff,
        }
    }

    pub fn from_wire_code(code: u16) -> Self {
        if code & UNKNOWN_WIRE_PREFIX != 0 {
            return Self::Unknown(code & !UNKNOWN_WIRE_PREFIX);
        }
        match code {
            0x0101..=0x0114 => Self::F((code - 0x0100) as u8),
            0x0061..=0x007a => Self::Char(char::from_u32(code as u32).unwrap()),
            0x0030..=0x0039 => Self::Digit((code - 0x0030) as u8),
            0x0020 => Self::Space,
            0x0009 => Self::Tab,
            0x001b => Self::Escape,
            0x000d => Self::Return,
            0x007f => Self::Delete,
            0x0008 => Self::Backspace,
            0x0201 => Self::ArrowUp,
            0x0202 => Self::ArrowDown,
            0x0203 => Self::ArrowLeft,
            0x0204 => Self::ArrowRight,
            0x0301 => Self::Modifier(ModType::Cmd, Side::Left),
            0x0302 => Self::Modifier(ModType::Cmd, Side::Right),
            0x0303 => Self::Modifier(ModType::Ctrl, Side::Left),
            0x0304 => Self::Modifier(ModType::Ctrl, Side::Right),
            0x0305 => Self::Modifier(ModType::Opt, Side::Left),
            0x0306 => Self::Modifier(ModType::Opt, Side::Right),
            0x0307 => Self::Modifier(ModType::Shift, Side::Left),
            0x0308 => Self::Modifier(ModType::Shift, Side::Right),
            code @ (0x0021 | 0x0027 | 0x002c | 0x002d | 0x002e | 0x002f | 0x003b | 0x003d
            | 0x005b | 0x005c | 0x005d | 0x0060) => {
                Self::Punct(char::from_u32(code as u32).unwrap())
            }
            other => Self::Unknown(other),
        }
    }

    pub fn name(self) -> Option<&'static str> {
        Some(match self {
            Self::F(1) => "f1",
            Self::F(2) => "f2",
            Self::F(3) => "f3",
            Self::F(4) => "f4",
            Self::F(5) => "f5",
            Self::F(6) => "f6",
            Self::F(7) => "f7",
            Self::F(8) => "f8",
            Self::F(9) => "f9",
            Self::F(10) => "f10",
            Self::F(11) => "f11",
            Self::F(12) => "f12",
            Self::F(13) => "f13",
            Self::F(14) => "f14",
            Self::F(15) => "f15",
            Self::F(16) => "f16",
            Self::F(17) => "f17",
            Self::F(18) => "f18",
            Self::F(19) => "f19",
            Self::F(20) => "f20",
            Self::Char('a') => "a",
            Self::Char('b') => "b",
            Self::Char('c') => "c",
            Self::Char('d') => "d",
            Self::Char('e') => "e",
            Self::Char('f') => "f",
            Self::Char('g') => "g",
            Self::Char('h') => "h",
            Self::Char('i') => "i",
            Self::Char('j') => "j",
            Self::Char('k') => "k",
            Self::Char('l') => "l",
            Self::Char('m') => "m",
            Self::Char('n') => "n",
            Self::Char('o') => "o",
            Self::Char('p') => "p",
            Self::Char('q') => "q",
            Self::Char('r') => "r",
            Self::Char('s') => "s",
            Self::Char('t') => "t",
            Self::Char('u') => "u",
            Self::Char('v') => "v",
            Self::Char('w') => "w",
            Self::Char('x') => "x",
            Self::Char('y') => "y",
            Self::Char('z') => "z",
            Self::Digit(0) => "0",
            Self::Digit(1) => "1",
            Self::Digit(2) => "2",
            Self::Digit(3) => "3",
            Self::Digit(4) => "4",
            Self::Digit(5) => "5",
            Self::Digit(6) => "6",
            Self::Digit(7) => "7",
            Self::Digit(8) => "8",
            Self::Digit(9) => "9",
            Self::Space => "space",
            Self::Tab => "tab",
            Self::Escape => "escape",
            Self::Return => "return",
            Self::Delete => "delete",
            Self::Backspace => "backspace",
            Self::ArrowUp => "up",
            Self::ArrowDown => "down",
            Self::ArrowLeft => "left",
            Self::ArrowRight => "right",
            Self::Punct(';') => ";",
            Self::Punct(',') => ",",
            Self::Punct('.') => ".",
            Self::Punct('/') => "/",
            Self::Punct('\\') => "\\",
            Self::Punct('[') => "[",
            Self::Punct(']') => "]",
            Self::Punct('\'') => "'",
            Self::Punct('`') => "`",
            Self::Punct('-') => "-",
            Self::Punct('=') => "=",
            _ => return None,
        })
    }
}

impl fmt::Display for Key {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self.name() {
            Some(name) => f.write_str(name),
            None => write!(f, "unknown({:#x})", self.wire_code()),
        }
    }
}

pub fn key_from_name(name: &str) -> Option<Key> {
    Some(match name {
        "f1" => Key::F(1),
        "f2" => Key::F(2),
        "f3" => Key::F(3),
        "f4" => Key::F(4),
        "f5" => Key::F(5),
        "f6" => Key::F(6),
        "f7" => Key::F(7),
        "f8" => Key::F(8),
        "f9" => Key::F(9),
        "f10" => Key::F(10),
        "f11" => Key::F(11),
        "f12" => Key::F(12),
        "f13" => Key::F(13),
        "f14" => Key::F(14),
        "f15" => Key::F(15),
        "f16" => Key::F(16),
        "f17" => Key::F(17),
        "f18" => Key::F(18),
        "f19" => Key::F(19),
        "f20" => Key::F(20),
        "a" => Key::Char('a'),
        "b" => Key::Char('b'),
        "c" => Key::Char('c'),
        "d" => Key::Char('d'),
        "e" => Key::Char('e'),
        "f" => Key::Char('f'),
        "g" => Key::Char('g'),
        "h" => Key::Char('h'),
        "i" => Key::Char('i'),
        "j" => Key::Char('j'),
        "k" => Key::Char('k'),
        "l" => Key::Char('l'),
        "m" => Key::Char('m'),
        "n" => Key::Char('n'),
        "o" => Key::Char('o'),
        "p" => Key::Char('p'),
        "q" => Key::Char('q'),
        "r" => Key::Char('r'),
        "s" => Key::Char('s'),
        "t" => Key::Char('t'),
        "u" => Key::Char('u'),
        "v" => Key::Char('v'),
        "w" => Key::Char('w'),
        "x" => Key::Char('x'),
        "y" => Key::Char('y'),
        "z" => Key::Char('z'),
        "0" => Key::Digit(0),
        "1" => Key::Digit(1),
        "2" => Key::Digit(2),
        "3" => Key::Digit(3),
        "4" => Key::Digit(4),
        "5" => Key::Digit(5),
        "6" => Key::Digit(6),
        "7" => Key::Digit(7),
        "8" => Key::Digit(8),
        "9" => Key::Digit(9),
        "space" => Key::Space,
        "tab" => Key::Tab,
        "return" => Key::Return,
        "escape" | "esc" => Key::Escape,
        "backspace" => Key::Backspace,
        "delete" => Key::Delete,
        "up" => Key::ArrowUp,
        "down" => Key::ArrowDown,
        "left" => Key::ArrowLeft,
        "right" => Key::ArrowRight,
        ";" | "," | "." | "/" | "\\" | "[" | "]" | "'" | "`" | "-" | "=" => {
            Key::Punct(name.chars().next().unwrap())
        }
        _ => return None,
    })
}

pub fn key_from_macos_keycode(code: u16) -> Key {
    match code {
        0x7A => Key::F(1),
        0x78 => Key::F(2),
        0x63 => Key::F(3),
        0x76 => Key::F(4),
        0x60 => Key::F(5),
        0x61 => Key::F(6),
        0x62 => Key::F(7),
        0x64 => Key::F(8),
        0x65 => Key::F(9),
        0x6D => Key::F(10),
        0x67 => Key::F(11),
        0x6F => Key::F(12),
        0x69 => Key::F(13),
        0x6B => Key::F(14),
        0x71 => Key::F(15),
        0x6A => Key::F(16),
        0x40 => Key::F(17),
        0x4F => Key::F(18),
        0x50 => Key::F(19),
        0x5A => Key::F(20),
        0x00 => Key::Char('a'),
        0x0B => Key::Char('b'),
        0x08 => Key::Char('c'),
        0x02 => Key::Char('d'),
        0x0E => Key::Char('e'),
        0x03 => Key::Char('f'),
        0x05 => Key::Char('g'),
        0x04 => Key::Char('h'),
        0x22 => Key::Char('i'),
        0x26 => Key::Char('j'),
        0x28 => Key::Char('k'),
        0x25 => Key::Char('l'),
        0x2E => Key::Char('m'),
        0x2D => Key::Char('n'),
        0x1F => Key::Char('o'),
        0x23 => Key::Char('p'),
        0x0C => Key::Char('q'),
        0x0F => Key::Char('r'),
        0x01 => Key::Char('s'),
        0x11 => Key::Char('t'),
        0x20 => Key::Char('u'),
        0x09 => Key::Char('v'),
        0x0D => Key::Char('w'),
        0x07 => Key::Char('x'),
        0x10 => Key::Char('y'),
        0x06 => Key::Char('z'),
        0x1D => Key::Digit(0),
        0x12 => Key::Digit(1),
        0x13 => Key::Digit(2),
        0x14 => Key::Digit(3),
        0x15 => Key::Digit(4),
        0x17 => Key::Digit(5),
        0x16 => Key::Digit(6),
        0x1A => Key::Digit(7),
        0x1C => Key::Digit(8),
        0x19 => Key::Digit(9),
        0x31 => Key::Space,
        0x30 => Key::Tab,
        0x24 => Key::Return,
        0x35 => Key::Escape,
        0x33 => Key::Backspace,
        0x75 => Key::Delete,
        0x7E => Key::ArrowUp,
        0x7D => Key::ArrowDown,
        0x7B => Key::ArrowLeft,
        0x7C => Key::ArrowRight,
        0x29 => Key::Punct(';'),
        0x2B => Key::Punct(','),
        0x2F => Key::Punct('.'),
        0x2C => Key::Punct('/'),
        0x2A => Key::Punct('\\'),
        0x21 => Key::Punct('['),
        0x1E => Key::Punct(']'),
        0x27 => Key::Punct('\''),
        0x32 => Key::Punct('`'),
        0x1B => Key::Punct('-'),
        0x18 => Key::Punct('='),
        0x37 => Key::Modifier(ModType::Cmd, Side::Left),
        0x36 => Key::Modifier(ModType::Cmd, Side::Right),
        0x38 => Key::Modifier(ModType::Shift, Side::Left),
        0x3C => Key::Modifier(ModType::Shift, Side::Right),
        0x3A => Key::Modifier(ModType::Opt, Side::Left),
        0x3D => Key::Modifier(ModType::Opt, Side::Right),
        0x3B => Key::Modifier(ModType::Ctrl, Side::Left),
        0x3E => Key::Modifier(ModType::Ctrl, Side::Right),
        other => Key::Unknown(other),
    }
}
