pub const LOCAL_VAD_VALUES: &[&str] = &["auto", "on", "off"];

pub const APPLE_LANGUAGE_VALUES: &[&str] = &[
    "ar-SA",
    "ca-ES",
    "cs-CZ",
    "da-DK",
    "de-AT",
    "de-CH",
    "de-DE",
    "el-GR",
    "en-AE",
    "en-AU",
    "en-CA",
    "en-GB",
    "en-ID",
    "en-IE",
    "en-IN",
    "en-NZ",
    "en-PH",
    "en-SA",
    "en-SG",
    "en-US",
    "en-ZA",
    "es-419",
    "es-CL",
    "es-CO",
    "es-ES",
    "es-MX",
    "es-US",
    "fi-FI",
    "fr-BE",
    "fr-CA",
    "fr-CH",
    "fr-FR",
    "he-IL",
    "hi-IN",
    "hi-IN-translit",
    "hi-Latn",
    "hr-HR",
    "hu-HU",
    "id-ID",
    "it-CH",
    "it-IT",
    "ja-JP",
    "ko-KR",
    "ms-MY",
    "nb-NO",
    "nl-BE",
    "nl-NL",
    "pl-PL",
    "pt-BR",
    "pt-PT",
    "ro-RO",
    "ru-RU",
    "sk-SK",
    "sv-SE",
    "th-TH",
    "tr-TR",
    "uk-UA",
    "vi-VN",
    "wuu-CN",
    "yue-CN",
    "zh-CN",
    "zh-HK",
    "zh-TW",
];

pub const DOUBAO_LANGUAGE_VALUES: &[&str] = &["auto", "zh-CN", "en-US"];

pub const TENCENT_ENGINE_MODEL_TYPE_VALUES: &[&str] = &[
    "16k_zh",
    "16k_zh_en",
    "16k_multi_lang",
    "16k_en_large",
    "16k_en",
    "16k_ja",
    "16k_ko",
    "16k_th",
    "16k_id",
    "16k_vi",
    "16k_ms",
    "16k_fil",
    "16k_pt",
    "16k_tr",
    "16k_ar",
    "16k_es",
    "16k_hi",
    "16k_fr",
    "16k_de",
];

pub fn values(values: &[&str]) -> Vec<String> {
    values.iter().map(|value| (*value).to_string()).collect()
}
